In [20]:
# list
lst1 = [1,2.5,3,4,5,6]
lst2 = ['string','another string','yet another']

lst3 = ['string', 1.3, 5, [1, 'second string'], {'John':'34-555-1234'}]

In [21]:
# lst1:
#     0 -> (type: int, value: 1)
#     1 -> (type:float, value:2.5)
#     ...
#     5 -> (type: int, value: 6)

# arr1 = 1|2|3|2|3
    
# lst2:
#     0 -> (type:string, value: 'string')
#     1 -> (type:string, value: 'another string')
#     2 -> (type:string, value: 'yet another')
    
# etc.

In [3]:
import numpy as np

In [4]:
a = np.random.random((5,10,4))
print(a)
print(type(a))

[[[0.74245547 0.12760932 0.49210254 0.87915901]
  [0.00701332 0.2943705  0.21568626 0.19307402]
  [0.534353   0.82848307 0.46242161 0.18990693]
  [0.12358122 0.61921861 0.3636087  0.08489821]
  [0.03145206 0.87617935 0.08361852 0.7821261 ]
  [0.17692483 0.03236404 0.14248048 0.63314403]
  [0.16009197 0.635244   0.7484573  0.47600743]
  [0.72169067 0.90033405 0.7521393  0.92862047]
  [0.39894361 0.25674564 0.91356466 0.1572497 ]
  [0.25366312 0.73787918 0.25818618 0.98622423]]

 [[0.74229442 0.75597986 0.88045661 0.13345078]
  [0.41045295 0.3375768  0.32614326 0.03803166]
  [0.38697732 0.75486792 0.78954322 0.53026676]
  [0.38941386 0.396807   0.48437036 0.77498831]
  [0.07622884 0.27308928 0.75902999 0.12427448]
  [0.53982537 0.3989817  0.88186648 0.5759216 ]
  [0.05755843 0.14941622 0.7329529  0.38104259]
  [0.89540137 0.83566902 0.67279451 0.77948897]
  [0.05192241 0.4037828  0.4868503  0.24930235]
  [0.34898375 0.07373179 0.99306942 0.0495083 ]]

 [[0.45280936 0.19447867 0.09484227 

In [5]:
print(a.shape)
print(a.size)

(5, 10, 4)
200


In [29]:
b = np.random.random((5,2,3))
print(b)

[[[0.23053075 0.05940174 0.4094255 ]
  [0.05869933 0.55887194 0.5420613 ]]

 [[0.3122423  0.16533808 0.32692855]
  [0.15341117 0.26954398 0.43537049]]

 [[0.09008593 0.79282408 0.86734226]
  [0.42669402 0.13739125 0.34977334]]

 [[0.63013572 0.18558752 0.52355376]
  [0.17542181 0.34691074 0.9779335 ]]

 [[0.89225961 0.01482495 0.30723407]
  [0.07010307 0.37831514 0.41922316]]]


In [30]:
c = np.random.random((2,3,4,5))
print(c)

[[[[7.76484065e-01 8.06243977e-01 6.11699264e-01 6.06963897e-01
    6.53628282e-01]
   [9.17214198e-01 7.29525427e-01 2.64113298e-01 2.73031057e-01
    8.21541320e-01]
   [5.28836505e-01 9.56728328e-01 1.57422955e-01 3.26409020e-01
    6.54124853e-01]
   [9.53300363e-01 2.84095093e-02 6.80023994e-01 3.49725579e-01
    9.99604584e-01]]

  [[1.02313869e-01 2.18532147e-01 7.91475065e-01 3.15770130e-01
    9.46924987e-01]
   [4.80086175e-01 9.31657982e-01 2.80309979e-01 7.04888241e-01
    4.42810829e-02]
   [8.79027887e-01 7.18025577e-01 5.38572275e-01 7.19867968e-01
    5.77941377e-01]
   [7.41607446e-01 5.15231091e-01 4.72058890e-04 5.55584004e-01
    1.65361539e-01]]

  [[3.97045562e-01 9.40529485e-01 6.05760829e-01 9.20559215e-01
    7.90986844e-03]
   [3.95994444e-01 1.09705671e-01 3.78260127e-02 1.91712386e-01
    3.58147225e-01]
   [9.12081295e-01 9.33325399e-01 2.08026476e-02 5.69097696e-01
    5.55475984e-01]
   [5.82003956e-02 4.75850290e-01 4.60760513e-01 7.10654996e-02
    6.89

In [34]:
print(c[1,2,3,4])

0.9051933119584123


In [38]:
# First row of matrix a
print(a)
print()
print(a[0])

[[0.10984685 0.26688918 0.32883169 0.51231315]
 [0.53410314 0.36449113 0.21651475 0.68929607]
 [0.99985949 0.38129149 0.9594366  0.86186655]
 [0.60919887 0.3511767  0.3037283  0.72194696]
 [0.46047714 0.31742554 0.58570295 0.93396298]
 [0.25288955 0.30621547 0.98584017 0.84730722]
 [0.19070735 0.31880166 0.06316382 0.75602694]
 [0.12171145 0.1456546  0.47157091 0.91642207]
 [0.81101242 0.57966451 0.17701395 0.21728656]
 [0.61811141 0.40894771 0.16825102 0.90377269]]

[0.10984685 0.26688918 0.32883169 0.51231315]


In [46]:
# First column of matrix a
print(a[:,0])
#print(np.vstack(a[:,0]))

[0.10984685 0.53410314 0.99985949 0.60919887 0.46047714 0.25288955
 0.19070735 0.12171145 0.81101242 0.61811141]


In [47]:
print(list(a[:,0]))

[0.1098468525523425, 0.5341031410492059, 0.9998594911964263, 0.6091988691554574, 0.46047714304150966, 0.25288955000979985, 0.19070734819378599, 0.12171145418066343, 0.8110124167776445, 0.6181114073721418]


In [41]:
# Value in the fifth row and third column of matrix a
print(a[4,2])

0.5857029549897795


In [50]:
# list equivalent
xlist = [[0.75069265, 0.53100122, 0.48637696, 0.20811268],
 [0.28855746, 0.86233589, 0.82170344, 0.64340505],
 [0.66165029 ,0.66529042 ,0.82118104 ,0.33245214],
 [0.23842237, 0.99227012, 0.70958494, 0.78773342],
 [0.59956754 ,0.72311601 ,0.78621408 ,0.48428124],
 [0.77134511, 0.90509481, 0.39564717, 0.70004292],
 [0.6590291  ,0.28677295 ,0.92953274 ,0.43896178],
 [0.22973736, 0.96647811, 0.51706048, 0.11653039],
 [0.27601849 ,0.7595283  ,0.80449362 ,0.42240349],
 [0.61892953, 0.31949189, 0.83564542, 0.43967919]]
#third value in fifth sublist
xlist[4][2]
#xlist[4,2]


0.78621408

In [51]:
ylist = list(a)
print(ylist)

[array([0.10984685, 0.26688918, 0.32883169, 0.51231315]), array([0.53410314, 0.36449113, 0.21651475, 0.68929607]), array([0.99985949, 0.38129149, 0.9594366 , 0.86186655]), array([0.60919887, 0.3511767 , 0.3037283 , 0.72194696]), array([0.46047714, 0.31742554, 0.58570295, 0.93396298]), array([0.25288955, 0.30621547, 0.98584017, 0.84730722]), array([0.19070735, 0.31880166, 0.06316382, 0.75602694]), array([0.12171145, 0.1456546 , 0.47157091, 0.91642207]), array([0.81101242, 0.57966451, 0.17701395, 0.21728656]), array([0.61811141, 0.40894771, 0.16825102, 0.90377269])]


In [52]:
ylist = [[x for x in row] for row in a]
print(ylist)

[[0.1098468525523425, 0.26688918213055235, 0.3288316903306522, 0.51231314914058], [0.5341031410492059, 0.36449113175812053, 0.21651475015117427, 0.6892960683480391], [0.9998594911964263, 0.38129149167427623, 0.9594366017509608, 0.8618665517178051], [0.6091988691554574, 0.35117670484590957, 0.3037283000163944, 0.7219469630147531], [0.46047714304150966, 0.31742554281120205, 0.5857029549897795, 0.9339629849905923], [0.25288955000979985, 0.30621546752270123, 0.9858401697944247, 0.8473072220186029], [0.19070734819378599, 0.3188016600857344, 0.06316382177255919, 0.7560269364833399], [0.12171145418066343, 0.14565459512052603, 0.47157091129049, 0.91642206763607], [0.8110124167776445, 0.5796645107142258, 0.17701395120178653, 0.21728655525992757], [0.6181114073721418, 0.40894771245013795, 0.16825101785403207, 0.9037726908161962]]


In [53]:
# First group of array c
print(c[0])

[[[7.76484065e-01 8.06243977e-01 6.11699264e-01 6.06963897e-01
   6.53628282e-01]
  [9.17214198e-01 7.29525427e-01 2.64113298e-01 2.73031057e-01
   8.21541320e-01]
  [5.28836505e-01 9.56728328e-01 1.57422955e-01 3.26409020e-01
   6.54124853e-01]
  [9.53300363e-01 2.84095093e-02 6.80023994e-01 3.49725579e-01
   9.99604584e-01]]

 [[1.02313869e-01 2.18532147e-01 7.91475065e-01 3.15770130e-01
   9.46924987e-01]
  [4.80086175e-01 9.31657982e-01 2.80309979e-01 7.04888241e-01
   4.42810829e-02]
  [8.79027887e-01 7.18025577e-01 5.38572275e-01 7.19867968e-01
   5.77941377e-01]
  [7.41607446e-01 5.15231091e-01 4.72058890e-04 5.55584004e-01
   1.65361539e-01]]

 [[3.97045562e-01 9.40529485e-01 6.05760829e-01 9.20559215e-01
   7.90986844e-03]
  [3.95994444e-01 1.09705671e-01 3.78260127e-02 1.91712386e-01
   3.58147225e-01]
  [9.12081295e-01 9.33325399e-01 2.08026476e-02 5.69097696e-01
   5.55475984e-01]
  [5.82003956e-02 4.75850290e-01 4.60760513e-01 7.10654996e-02
   6.89782857e-01]]]


In [54]:
# Second subgroup of the first group
print(c[0,1])

[[1.02313869e-01 2.18532147e-01 7.91475065e-01 3.15770130e-01
  9.46924987e-01]
 [4.80086175e-01 9.31657982e-01 2.80309979e-01 7.04888241e-01
  4.42810829e-02]
 [8.79027887e-01 7.18025577e-01 5.38572275e-01 7.19867968e-01
  5.77941377e-01]
 [7.41607446e-01 5.15231091e-01 4.72058890e-04 5.55584004e-01
  1.65361539e-01]]


In [60]:
# Fourth column of the second subgroup of the first group
# print(np.vstack(c[0,1,:,3]))
# print(c[0,1,2])
# print(list(c[0,1,:,3]))

weeknr = 0
print(c[:,weeknr])




[[[0.77648407 0.80624398 0.61169926 0.6069639  0.65362828]
  [0.9172142  0.72952543 0.2641133  0.27303106 0.82154132]
  [0.52883651 0.95672833 0.15742295 0.32640902 0.65412485]
  [0.95330036 0.02840951 0.68002399 0.34972558 0.99960458]]

 [[0.77413709 0.08507883 0.35140128 0.66259579 0.22741469]
  [0.0950434  0.4243884  0.51615559 0.40535992 0.77211401]
  [0.48837385 0.80882016 0.67532096 0.02443016 0.93483401]
  [0.73121141 0.71860348 0.81991655 0.99347888 0.89825212]]]


In [66]:
newarr = np.array([[0.6718173948698819, 0.662595795992], [0.2662825704884635, 0.19996310250953375]])
print(newarr)
#print(type(newarr[0,1]))

[[0.67181739 0.6625958 ]
 [0.26628257 0.1999631 ]]
<class 'numpy.float64'>


In [67]:
lst_lst = [[1,2,3],[4,5,6],[7,8,9]]
d = np.array(lst_lst)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [68]:
print(a)

[[0.10984685 0.26688918 0.32883169 0.51231315]
 [0.53410314 0.36449113 0.21651475 0.68929607]
 [0.99985949 0.38129149 0.9594366  0.86186655]
 [0.60919887 0.3511767  0.3037283  0.72194696]
 [0.46047714 0.31742554 0.58570295 0.93396298]
 [0.25288955 0.30621547 0.98584017 0.84730722]
 [0.19070735 0.31880166 0.06316382 0.75602694]
 [0.12171145 0.1456546  0.47157091 0.91642207]
 [0.81101242 0.57966451 0.17701395 0.21728656]
 [0.61811141 0.40894771 0.16825102 0.90377269]]


In [72]:
# Sum of all elements in matrix a
print(np.sum(a))

19.768731031220522


In [71]:
# Sum of each column in matrix a
print(np.sum(a, axis=0))

[4.70791767 3.440558   4.26005417 7.36020119]


In [73]:
# Sum of each row in matrix a
print(np.sum(a, axis=1))

[1.21788087 1.80440509 3.20245414 1.98605084 2.29756863 2.39225241
 1.32869977 1.65535903 1.78497743 2.09908283]


In [74]:
print(b)

[[[0.23053075 0.05940174 0.4094255 ]
  [0.05869933 0.55887194 0.5420613 ]]

 [[0.3122423  0.16533808 0.32692855]
  [0.15341117 0.26954398 0.43537049]]

 [[0.09008593 0.79282408 0.86734226]
  [0.42669402 0.13739125 0.34977334]]

 [[0.63013572 0.18558752 0.52355376]
  [0.17542181 0.34691074 0.9779335 ]]

 [[0.89225961 0.01482495 0.30723407]
  [0.07010307 0.37831514 0.41922316]]]


In [75]:
# Sum of all the elements in the first two groups of array b
print(b[:2])
np.sum(b[:2])

[[[0.23053075 0.05940174 0.4094255 ]
  [0.05869933 0.55887194 0.5420613 ]]

 [[0.3122423  0.16533808 0.32692855]
  [0.15341117 0.26954398 0.43537049]]]


3.521825135786238

In [78]:
# Mean of all elements in matrix a
print(np.mean(a))
#?a
#a. + Tab

0.49421827578051303


0.49421827578051303

In [79]:
# Mean of each column in matrix a
print(np.mean(a, axis=0))

[0.47079177 0.3440558  0.42600542 0.73602012]


In [80]:
# Mean of each row in matrix a
print(np.mean(a, axis=1))

[0.30447022 0.45110127 0.80061353 0.49651271 0.57439216 0.5980631
 0.33217494 0.41383976 0.44624436 0.52477071]


In [81]:
# Mean of all the elements in the first two groups of array b
np.mean(b[:2])

0.2934854279821865

In [82]:
x = c[0,0]
print(x)

[[0.77648407 0.80624398 0.61169926 0.6069639  0.65362828]
 [0.9172142  0.72952543 0.2641133  0.27303106 0.82154132]
 [0.52883651 0.95672833 0.15742295 0.32640902 0.65412485]
 [0.95330036 0.02840951 0.68002399 0.34972558 0.99960458]]


In [83]:
y = c[0,1]
print(y)

[[1.02313869e-01 2.18532147e-01 7.91475065e-01 3.15770130e-01
  9.46924987e-01]
 [4.80086175e-01 9.31657982e-01 2.80309979e-01 7.04888241e-01
  4.42810829e-02]
 [8.79027887e-01 7.18025577e-01 5.38572275e-01 7.19867968e-01
  5.77941377e-01]
 [7.41607446e-01 5.15231091e-01 4.72058890e-04 5.55584004e-01
  1.65361539e-01]]


In [86]:
# Add elements of x and y together
print(np.add(x, y))

[[0.87879793 1.02477612 1.40317433 0.92273403 1.60055327]
 [1.39730037 1.66118341 0.54442328 0.9779193  0.8658224 ]
 [1.40786439 1.67475391 0.69599523 1.04627699 1.23206623]
 [1.69490781 0.5436406  0.68049605 0.90530958 1.16496612]]


In [87]:
x*10

array([[7.76484065, 8.06243977, 6.11699264, 6.06963897, 6.53628282],
       [9.17214198, 7.29525427, 2.64113298, 2.73031057, 8.2154132 ],
       [5.28836505, 9.56728328, 1.57422955, 3.2640902 , 6.54124853],
       [9.53300363, 0.28409509, 6.80023994, 3.49725579, 9.99604584]])

In [88]:
# Subtract elements of x from elements of y
print(np.subtract(y, x))

[[-0.6741702  -0.58771183  0.1797758  -0.29119377  0.29329671]
 [-0.43712802  0.20213255  0.01619668  0.43185718 -0.77726024]
 [ 0.35019138 -0.23870275  0.38114932  0.39345895 -0.07618348]
 [-0.21169292  0.48682158 -0.67955193  0.20585842 -0.83424304]]


In [89]:
# Multiply elements of x and y together
print(np.multiply(x, y))

[[7.94450886e-02 1.76190227e-01 4.84144715e-01 1.91661069e-01
  6.18936952e-01]
 [4.40341856e-01 6.79668188e-01 7.40335931e-02 1.92456381e-01
  3.63787393e-02]
 [4.64862036e-01 6.86955410e-01 8.47836388e-02 2.34971398e-01
  3.78045818e-01]
 [7.06974647e-01 1.46374625e-02 3.21011372e-04 1.94301937e-01
  1.65296153e-01]]


In [94]:
# Divide elements of y by elements of x
print(x)
print(c[1,0,0])
print(np.divide(x, c[1,0,0]))

[[0.77648407 0.80624398 0.61169926 0.6069639  0.65362828]
 [0.9172142  0.72952543 0.2641133  0.27303106 0.82154132]
 [0.52883651 0.95672833 0.15742295 0.32640902 0.65412485]
 [0.95330036 0.02840951 0.68002399 0.34972558 0.99960458]]
[0.77413709 0.08507883 0.35140128 0.66259579 0.22741469]
[[ 1.00303173  9.47643481  1.74074285  0.91603947  2.87416912]
 [ 1.18482141  8.57469991  0.75160028  0.41206277  3.61252528]
 [ 0.6831303  11.24519859  0.44798629  0.49262163  2.87635267]
 [ 1.23143611  0.33391984  1.93517792  0.52781135  4.39551455]]


In [95]:
print(d)
print(d%2==0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False  True False]
 [ True False  True]
 [False  True False]]


In [ ]:
%%time
for i in range(100000):
    z = np.multiply(x, y)

In [ ]:
import random
x_list = [[random.random() for j in range(5)] for i in range(4)]
y_list = [[random.random() for j in range(5)] for i in range(4)]

In [ ]:
x_list

In [ ]:
%%time
for i in range(100000):
    z = []
    for i in range(4):
        innerlist = []
        for j in range(5):
            innerlist.append(x_list[i][j]*y_list[i][j])
        z.append(innerlist)

#print(z)
    

In [ ]:
%%time
for i in range(100):
    x_new = [j for j in range(1000)]
    

In [ ]:
%%time
for i in range(100):
    x = []
    for j in range(1000):
        x.append(j)
    
#print(x)

In [ ]:
# Install a pip package in the current Jupyter kernel
import sys
!{sys.executable} -m pip3 install numpy