# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.19.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.06099631 0.69828728 0.8729253  0.74971691 0.9162324 ]
  [0.13354842 0.90379456 0.85858169 0.72792694 0.79191822]
  [0.89064847 0.97338695 0.28084119 0.04933401 0.25830648]]

 [[0.915803   0.95743389 0.20480855 0.25937482 0.73292556]
  [0.32880825 0.09263819 0.32770128 0.26079221 0.43000821]
  [0.18237069 0.3120574  0.79775776 0.98095463 0.37393761]]]


In [4]:
# Method 2
a = np.random.uniform(0,1,(2,3,5))
print(a)

[[[0.96344249 0.43001879 0.46521636 0.72004308 0.34983335]
  [0.14622864 0.35427591 0.06896681 0.00375272 0.67409856]
  [0.39812903 0.16489658 0.529987   0.74788115 0.07853583]]

 [[0.35460367 0.15810692 0.9300802  0.79907352 0.32294628]
  [0.54945511 0.86715496 0.42762452 0.2618994  0.79592025]
  [0.69020535 0.07943121 0.21026792 0.13352356 0.67038229]]]


In [32]:
# Method 3
from random import random

a = np.random.randint(0,101, (2,3,5))
print(a)

[[[99 71 98 10 53]
  [87 27 89  1 97]
  [92  2 52 49 15]]

 [[97 24 13 13 15]
  [ 1 54 53 74 77]
  [56  1 62 77 17]]]


#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.92272623 0.41774762 0.40161261 0.04922266 0.43094794]
  [0.98198193 0.5830641  0.95784867 0.06073866 0.79745993]
  [0.74058518 0.24141192 0.02727748 0.97752878 0.63595715]]

 [[0.72296745 0.8905472  0.59562659 0.48627427 0.95848058]
  [0.6851408  0.4990804  0.06107971 0.71000119 0.08648818]
  [0.19013572 0.08378064 0.98697333 0.99061416 0.76110947]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.full((5,2,3), 1)

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
print(a.size)
print(b.size)
print(a.size == b.size)

30
30
True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
print(np.add(a, b))

'''
It's not possible because arrays have different shapes.
'''

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c = b.transpose(1, 2, 0)
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = np.add(a, c)
print(d)

'''
This works because arrays a & c have the same shape.
'''

[[[1.92272623 1.41774762 1.40161261 1.04922266 1.43094794]
  [1.98198193 1.5830641  1.95784867 1.06073866 1.79745993]
  [1.74058518 1.24141192 1.02727748 1.97752878 1.63595715]]

 [[1.72296745 1.8905472  1.59562659 1.48627427 1.95848058]
  [1.6851408  1.4990804  1.06107971 1.71000119 1.08648818]
  [1.19013572 1.08378064 1.98697333 1.99061416 1.76110947]]]


'\nThis works because arrays a & c have the same shape.\n'

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here

print(a)
print('*'*60)
print(d)

'''
Each value in array d is more than each value in array a situated in the same position by 1, because we added array c (which
contains from 1's) to create array d.
'''

[[[0.92272623 0.41774762 0.40161261 0.04922266 0.43094794]
  [0.98198193 0.5830641  0.95784867 0.06073866 0.79745993]
  [0.74058518 0.24141192 0.02727748 0.97752878 0.63595715]]

 [[0.72296745 0.8905472  0.59562659 0.48627427 0.95848058]
  [0.6851408  0.4990804  0.06107971 0.71000119 0.08648818]
  [0.19013572 0.08378064 0.98697333 0.99061416 0.76110947]]]
************************************************************
[[[1.92272623 1.41774762 1.40161261 1.04922266 1.43094794]
  [1.98198193 1.5830641  1.95784867 1.06073866 1.79745993]
  [1.74058518 1.24141192 1.02727748 1.97752878 1.63595715]]

 [[1.72296745 1.8905472  1.59562659 1.48627427 1.95848058]
  [1.6851408  1.4990804  1.06107971 1.71000119 1.08648818]
  [1.19013572 1.08378064 1.98697333 1.99061416 1.76110947]]]


"\nEach value in array d is more than each value in array a situated in the same position by 1, because we added array c (which\ncontains from 1's) to create array d.\n"

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = np.multiply(a, c)
print(e)

[[[0.92272623 0.41774762 0.40161261 0.04922266 0.43094794]
  [0.98198193 0.5830641  0.95784867 0.06073866 0.79745993]
  [0.74058518 0.24141192 0.02727748 0.97752878 0.63595715]]

 [[0.72296745 0.8905472  0.59562659 0.48627427 0.95848058]
  [0.6851408  0.4990804  0.06107971 0.71000119 0.08648818]
  [0.19013572 0.08378064 0.98697333 0.99061416 0.76110947]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here

print(a == e)

'''
Arrays a and e are identical because multiplication to 1 doesn't change the value.
'''

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


"\nArrays a and e are identical because multiplication to 1 doesn't change the value.\n"

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max, d_min, d_mean)

1.9906141633277958 1.027277482376572 1.5644803524341906


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty((2, 3, 5), float)
print(f)

[[[0.92272623 0.41774762 0.40161261 0.04922266 0.43094794]
  [0.98198193 0.5830641  0.95784867 0.06073866 0.79745993]
  [0.74058518 0.24141192 0.02727748 0.97752878 0.63595715]]

 [[0.72296745 0.8905472  0.59562659 0.48627427 0.95848058]
  [0.6851408  0.4990804  0.06107971 0.71000119 0.08648818]
  [0.19013572 0.08378064 0.98697333 0.99061416 0.76110947]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [24]:
'''
**For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
**If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
**If a value equals to d_mean, assign 50 to the corresponding value in f.
**Assign 0 to the corresponding value(s) in f for d_min in d.
**Assign 100 to the corresponding value(s) in f for d_max in d.
'''

# your code here

'''
Expresions included in this comment doesn't solve the task but it's a nice way to apply simple condition to each element in 
array and I would like to keep it as a tip for the future.
f[d == d_max] = 100
f[d < d_mean] = 5
'''

for x in range(d.shape[0]):
    for y in range(d.shape[1]):
        for z in range(d.shape[2]):
            if d[x][y][z] == d_max:
                f[x][y][z] = 100
            if d[x][y][z] == d_min:
                f[x][y][z] = 0
            if d[x][y][z] == d_mean:
                f[x][y][z] = 50
            if d[x][y][z] > d_min and d[x][y][z] < d_mean:
                f[x][y][z] = 25
            if d[x][y][z] < d_max and d[x][y][z] > d_mean:
                f[x][y][z] = 75

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [25]:
# your code here
print(d)
print('*'*60)
print(f)

[[[1.92272623 1.41774762 1.40161261 1.04922266 1.43094794]
  [1.98198193 1.5830641  1.95784867 1.06073866 1.79745993]
  [1.74058518 1.24141192 1.02727748 1.97752878 1.63595715]]

 [[1.72296745 1.8905472  1.59562659 1.48627427 1.95848058]
  [1.6851408  1.4990804  1.06107971 1.71000119 1.08648818]
  [1.19013572 1.08378064 1.98697333 1.99061416 1.76110947]]]
************************************************************
[[[75 25 25 25 25]
  [75 75 75 25 75]
  [75 25 0 75 75]]

 [[75 75 75 25 75]
  [75 25 25 75 25]
  [25 25 75 100 75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [26]:
# your code here

f = f.astype('object') 

for x in range(d.shape[0]):
    for y in range(d.shape[1]):
        for z in range(d.shape[2]):
            if d[x][y][z] == d_max:
                f[x][y][z] = 'E'
            if d[x][y][z] == d_min:
                f[x][y][z] = 'A'
            if d[x][y][z] == d_mean:
                f[x][y][z] = 'C'
            if d[x][y][z] > d_min and d[x][y][z] < d_mean:
                f[x][y][z] = 'B'
            if d[x][y][z] < d_max and d[x][y][z] > d_mean:
                f[x][y][z] = 'D'

                
# Debugging:
print(f"d_max is {d_max}. d_min is {d_min}. d_mean is {d_mean}.")
print('*'*60)
print(f)
print('*'*60)
print(d)

d_max is 1.9906141633277958. d_min is 1.027277482376572. d_mean is 1.5644803524341906.
************************************************************
[[['D' 'B' 'B' 'B' 'B']
  ['D' 'D' 'D' 'B' 'D']
  ['D' 'B' 'A' 'D' 'D']]

 [['D' 'D' 'D' 'B' 'D']
  ['D' 'B' 'B' 'D' 'B']
  ['B' 'B' 'D' 'E' 'D']]]
************************************************************
[[[1.92272623 1.41774762 1.40161261 1.04922266 1.43094794]
  [1.98198193 1.5830641  1.95784867 1.06073866 1.79745993]
  [1.74058518 1.24141192 1.02727748 1.97752878 1.63595715]]

 [[1.72296745 1.8905472  1.59562659 1.48627427 1.95848058]
  [1.6851408  1.4990804  1.06107971 1.71000119 1.08648818]
  [1.19013572 1.08378064 1.98697333 1.99061416 1.76110947]]]
