# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [6]:
# your code here
import sys
!{sys.executable} -m pip install numpy
import numpy as np

You should consider upgrading via the 'pip install --upgrade pip' command.


#### 2. Print your NumPy version.

In [ ]:
# your code here
#numpy-1.19.1

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [11]:
# Method 1
a = np.random.random((2,3,5))

In [9]:
# Method 2

In [ ]:
# Method 3

#### 4. Print *a*.


In [10]:
# your code here
print(a)

[[[0.99675168 0.59180268 0.57321828 0.39977096 0.60045244]
  [0.96868893 0.43754692 0.93640526 0.7161501  0.08072836]
  [0.52205587 0.88478946 0.20957094 0.0420161  0.59102096]]

 [[0.32743153 0.91644033 0.42088552 0.10269102 0.46955081]
  [0.64766437 0.07328736 0.24486821 0.50966031 0.62633251]
  [0.6974052  0.3715333  0.05724258 0.10003356 0.77785892]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [17]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [18]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [27]:
# your code here
np.size(a)
np.size(b)
np.size(a)==np.size(b)

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [28]:
# your answer here
np.add(a, b)
#np because their shapes differ

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [29]:
# your code here
c = b.reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [33]:
# your code/answer here
d=np.add(a,c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [36]:
# your code/answer here
print(a)
print()
print(d)
#the values of d are just each value of a plus 1, because all the values from b  equal 1

[[[0.49830675 0.19100517 0.10302733 0.75911027 0.85366716]
  [0.97676029 0.84995643 0.95107736 0.33020686 0.81985778]
  [0.82037497 0.64266442 0.62717925 0.71812581 0.4115233 ]]

 [[0.92815962 0.86912595 0.43496696 0.54942633 0.08180615]
  [0.73871249 0.7015752  0.89214323 0.32593758 0.1017211 ]
  [0.02597322 0.12958577 0.59878796 0.19457638 0.78831652]]]

[[[1.49830675 1.19100517 1.10302733 1.75911027 1.85366716]
  [1.97676029 1.84995643 1.95107736 1.33020686 1.81985778]
  [1.82037497 1.64266442 1.62717925 1.71812581 1.4115233 ]]

 [[1.92815962 1.86912595 1.43496696 1.54942633 1.08180615]
  [1.73871249 1.7015752  1.89214323 1.32593758 1.1017211 ]
  [1.02597322 1.12958577 1.59878796 1.19457638 1.78831652]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [37]:
# your code here
e = np.multiply(a, c)
print(e)

[[[0.49830675 0.19100517 0.10302733 0.75911027 0.85366716]
  [0.97676029 0.84995643 0.95107736 0.33020686 0.81985778]
  [0.82037497 0.64266442 0.62717925 0.71812581 0.4115233 ]]

 [[0.92815962 0.86912595 0.43496696 0.54942633 0.08180615]
  [0.73871249 0.7015752  0.89214323 0.32593758 0.1017211 ]
  [0.02597322 0.12958577 0.59878796 0.19457638 0.78831652]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [38]:
# your code/answer here
np.size(a)
np.size(e)
np.size(a)==np.size(e)
#because each value*1=the same value

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [41]:
# your code here
d_max=np.max(d)
print(d_max)

d_min=np.min(d)
print(d_min)

d_mean=np.mean(d)
print(d_mean)

1.9767602881341957
1.025973219452545
1.5637885861191854


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [86]:
# your code here
f = np.empty((2,3,5))
f = f*0
print(f)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [87]:
# your code here
#it should work, np.insert exists, but something is not right about the syntaxis I guess


for value in np.nditer(d):
    if value > d_min and value < d_mean:
        np.insert(f, 0, 25)
    if value > d_mean and value < d_max:
        np.insert(f, 0, 75)
    if value == d_mean:
        np.insert(f, 0, 50)
    if value == d_min:
        np.insert(f, 0, 0)
    if value == d_max:
        np.insert(f, 0, 100)
        
print(f)



[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here