# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [4]:
# your code here
print(np)

<module 'numpy' from 'C:\\Users\\svvan\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [30]:
# Method 1
a = np.random.randint(5, size=(2, 3, 5))
print(a)

[[[1 4 3 0 3]
  [1 0 3 3 0]
  [0 3 0 2 0]]

 [[1 4 4 2 4]
  [1 1 1 2 3]
  [3 1 0 1 4]]]


In [43]:
# Method 2
b = np.random.random((2,3,5))
print(b)

[[[0.30459165 0.97326048 0.91618056 0.58248502 0.41535923]
  [0.78727734 0.79679687 0.73449609 0.36835624 0.60698399]
  [0.51140879 0.26000189 0.59110564 0.10765603 0.99901349]]

 [[0.79283091 0.67039699 0.53394324 0.86875712 0.99755685]
  [0.24307011 0.47298505 0.84005489 0.14342008 0.05053776]
  [0.38079371 0.37668136 0.68585837 0.66828731 0.05918987]]]


In [90]:
# Method 3

c = np.array([2,3])
c

array([2, 3])

#### 4. Print *a*.


In [39]:
# your code here
print(a)

[[[1 4 3 0 3]
  [1 0 3 3 0]
  [0 3 0 2 0]]

 [[1 4 4 2 4]
  [1 1 1 2 3]
  [3 1 0 1 4]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [54]:
# your code here
b = np.ones((5,2,3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 6. Print *b*.


In [55]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [58]:
# your code here
print("Size a:",a.size)
print("Size b:",b.size)
if a.size == b.size:
    print("a & b have the same size")
    
else:
    print("a & b have different sizes")

Size a: 30
Size b: 30
a & b have the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [59]:
# your answer here
print(np.add(a, b))
# you cannot add them together since they have different dimensions

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [89]:
# your code here
c = np.transpose(b,[1,2,0])
print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [91]:
# your code/answer here
d = np.add(a, c)
print(d)
#Not it works since the dimensions are equal. (2x3x5) = (2x3x5)

[[[2. 5. 4. 1. 4.]
  [2. 1. 4. 4. 1.]
  [1. 4. 1. 3. 1.]]

 [[2. 5. 5. 3. 5.]
  [2. 2. 2. 3. 4.]
  [4. 2. 1. 2. 5.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [76]:
# your code/answer here
print(a)
print(d)
# Array d - Array a = Array c

[[[1 4 1 1 2]
  [0 2 0 1 0]
  [1 3 4 2 2]]

 [[0 1 3 3 3]
  [4 4 0 2 2]
  [0 1 4 4 2]]]
[[[2. 5. 2. 2. 3.]
  [1. 3. 1. 2. 1.]
  [2. 4. 5. 3. 3.]]

 [[1. 2. 4. 4. 4.]
  [5. 5. 1. 3. 3.]
  [1. 2. 5. 5. 3.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [93]:
# your code here
e = np.multiply(a, c)
print(e)

[[[1. 4. 3. 0. 3.]
  [1. 0. 3. 3. 0.]
  [0. 3. 0. 2. 0.]]

 [[1. 4. 4. 2. 4.]
  [1. 1. 1. 2. 3.]
  [3. 1. 0. 1. 4.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here
# Array e does not equal array A. Array e does equal: Array e divided by Array C

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [77]:
# your code here
d_mean = np.mean(d)
d_max = np.max(d)
d_min = np.min(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [98]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [87]:
# your code here
for x in range(d.shape[0]):
    for y in range(d.shape[1]):
        for z in range(d.shape[2]):
            if d[x][y][z] > d_min and d[x][y][z] < d_mean:
                f[x][y][z] = 25
            if d[x][y][z] > d_mean and d[x][y][z] < d_max:
                f[x][y][z] = 75
            if d[x][y][z] == d_mean:
                f[x][y][z] = 50
            if d[x][y][z] == d_min:
                f[x][y][z] = 0
            if d[x][y][z] == d_max:
                f[x][y][z] = 100

print(d)
print("\n")
print(d_min, d_max, d_mean) 
print("\n")
print(f)
            

[[[2. 5. 2. 2. 3.]
  [1. 3. 1. 2. 1.]
  [2. 4. 5. 3. 3.]]

 [[1. 2. 4. 4. 4.]
  [5. 5. 1. 3. 3.]
  [1. 2. 5. 5. 3.]]]


1.0 5.0 2.9


[[[ 25. 100.  25.  25.  75.]
  [  0.  75.   0.  25.   0.]
  [ 25.  75. 100.  75.  75.]]

 [[  0.  25.  75.  75.  75.]
  [100. 100.   0.  75.  75.]
  [  0.  25. 100. 100.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [88]:
# your code here
print(d)
print("\n")
print(d_min, d_max, d_mean) 
print("\n")
print(f)

[[[2. 5. 2. 2. 3.]
  [1. 3. 1. 2. 1.]
  [2. 4. 5. 3. 3.]]

 [[1. 2. 4. 4. 4.]
  [5. 5. 1. 3. 3.]
  [1. 2. 5. 5. 3.]]]


1.0 5.0 2.9


[[[ 25. 100.  25.  25.  75.]
  [  0.  75.   0.  25.   0.]
  [ 25.  75. 100.  75.  75.]]

 [[  0.  25.  75.  75.  75.]
  [100. 100.   0.  75.  75.]
  [  0.  25. 100. 100.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here