# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [56]:
import numpy as np


#### 2. Print your NumPy version.

In [57]:
# your code here

print(np.__version__)

1.19.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [8]:
# Method 1

a = np.random.random((2,3,5))


In [ ]:
# Method 2

In [ ]:
# Method 3

#### 4. Print *a*.


In [9]:
# your code here

print(a)

[[[0.92334844 0.95546333 0.3837068  0.37050831 0.78765271]
  [0.22745699 0.07993455 0.14022902 0.37513633 0.41223459]
  [0.98755707 0.816922   0.51418494 0.77326649 0.67206569]]

 [[0.83835962 0.9533165  0.99208408 0.09319057 0.28134257]
  [0.24498259 0.31416729 0.14456683 0.78223996 0.20285123]
  [0.8902721  0.50298882 0.98224573 0.66927149 0.05423517]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [11]:
# your code here

b = np.ones((5,2,3))

#### 6. Print *b*.


In [12]:
# your code here
b = np.ones((5,2,3))
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [15]:
# your code here

print(a.size)
print(b.size)

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [17]:
# your answer here

print(np.add(a,b))

# No, because they don't have the same shape ; a is (2,3,5) and b is (5,2,3)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [30]:
# your code here

# c = np.transpose(b,a).size => didn't work
# b = np.transpose(b,a).shape => didn't work


# solution 1
c = np.ones((2,3,5))

print(c)
print()

# solution2
c2 = np.transpose(b)

print(c2)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [25]:
# your code/answer here

print(np.add(a,c))

[[[1.92334844 1.95546333 1.3837068  1.37050831 1.78765271]
  [1.22745699 1.07993455 1.14022902 1.37513633 1.41223459]
  [1.98755707 1.816922   1.51418494 1.77326649 1.67206569]]

 [[1.83835962 1.9533165  1.99208408 1.09319057 1.28134257]
  [1.24498259 1.31416729 1.14456683 1.78223996 1.20285123]
  [1.8902721  1.50298882 1.98224573 1.66927149 1.05423517]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [27]:
# your code/answer here

d = np.add(a,c)

print(a)
print()
print(d)

# Both arrays have the same exact values , they are not being sum

[[[0.92334844 0.95546333 0.3837068  0.37050831 0.78765271]
  [0.22745699 0.07993455 0.14022902 0.37513633 0.41223459]
  [0.98755707 0.816922   0.51418494 0.77326649 0.67206569]]

 [[0.83835962 0.9533165  0.99208408 0.09319057 0.28134257]
  [0.24498259 0.31416729 0.14456683 0.78223996 0.20285123]
  [0.8902721  0.50298882 0.98224573 0.66927149 0.05423517]]]

[[[1.92334844 1.95546333 1.3837068  1.37050831 1.78765271]
  [1.22745699 1.07993455 1.14022902 1.37513633 1.41223459]
  [1.98755707 1.816922   1.51418494 1.77326649 1.67206569]]

 [[1.83835962 1.9533165  1.99208408 1.09319057 1.28134257]
  [1.24498259 1.31416729 1.14456683 1.78223996 1.20285123]
  [1.8902721  1.50298882 1.98224573 1.66927149 1.05423517]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [32]:
# your code here

e = np.multiply(a, c)

print(e)

[[[0.92334844 0.95546333 0.3837068  0.37050831 0.78765271]
  [0.22745699 0.07993455 0.14022902 0.37513633 0.41223459]
  [0.98755707 0.816922   0.51418494 0.77326649 0.67206569]]

 [[0.83835962 0.9533165  0.99208408 0.09319057 0.28134257]
  [0.24498259 0.31416729 0.14456683 0.78223996 0.20285123]
  [0.8902721  0.50298882 0.98224573 0.66927149 0.05423517]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [33]:
# your code/answer here

# Yes e is equal to a 
# In exercise 11 it did't actually multiplied the values a*c, maybe because they had the same values ?

print(e)
print()
print(a)

[[[0.92334844 0.95546333 0.3837068  0.37050831 0.78765271]
  [0.22745699 0.07993455 0.14022902 0.37513633 0.41223459]
  [0.98755707 0.816922   0.51418494 0.77326649 0.67206569]]

 [[0.83835962 0.9533165  0.99208408 0.09319057 0.28134257]
  [0.24498259 0.31416729 0.14456683 0.78223996 0.20285123]
  [0.8902721  0.50298882 0.98224573 0.66927149 0.05423517]]]

[[[0.92334844 0.95546333 0.3837068  0.37050831 0.78765271]
  [0.22745699 0.07993455 0.14022902 0.37513633 0.41223459]
  [0.98755707 0.816922   0.51418494 0.77326649 0.67206569]]

 [[0.83835962 0.9533165  0.99208408 0.09319057 0.28134257]
  [0.24498259 0.31416729 0.14456683 0.78223996 0.20285123]
  [0.8902721  0.50298882 0.98224573 0.66927149 0.05423517]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [37]:
# your code here

d_mean = np.mean(d)
print(d_mean)

d_min = np.min(d)
print(d_min)

d_max = np.max(d)
print(d_max)

1.5455260603256835
1.054235172427816
1.9920840834869042


15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [65]:
# your code here

f = np.empty((2,3,5))





#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [74]:
# I could'nt get the loop to iterate through the array b

# 25 if d = larger than d_min but smaller than d_mean
# 75 if d = larger than d_mean but smaller than d_max
# 50 if d = equals to d_mean
# 0 if d = d_min

new_f = [] 

d_mean = np.mean(d)
d_min = np.min(d)
d_max = np.max(d)


for i in d: 
    if i == d_min:
        i == 0
        new_f.append(i)
    if i >= d_min or i.any() <= d_mean:
        i == 25
        new_f.append(i)
    elif i >= d_mean or i.any() <= d_max:
        i == 75
        new_f.append(i)
    elif i.any() == d_mean: 
        i == 50
        new_f.append(i)
    elif i == d_max:
        i == 100
        new_f.append(i)

print()
print(new_f)
            

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [31]:
bonus = [[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]

new_bonus =[]

# Unfortunately the loop can't replace the values for letters

for i in bonus:
    print(i)    
    for number in groups:
        print(number)
        if number == 0:
            number == "A"
            new_bonus.append(number)
        if number == 25:
            number == "B"
            new_bonus.append(number)
        elif number == 50:
            number == "C"
            new_bonus.append(number)
        elif number == 75: 
            number == "D"
            new_bonus.append(number)
        elif number == 100:
            number == "E"
            new_bonus.append(number)
               

print(new_bonus)

[[75.0, 75.0, 75.0, 25.0, 75.0], [75.0, 75.0, 25.0, 25.0, 25.0], [75.0, 25.0, 75.0, 75.0, 75.0]]
[25.0, 25.0, 25.0, 25.0, 100.0]
[75.0, 75.0, 75.0, 75.0, 75.0]
[25.0, 75.0, 0.0, 75.0, 75.0]
[[25.0, 25.0, 25.0, 25.0, 100.0], [75.0, 75.0, 75.0, 75.0, 75.0], [25.0, 75.0, 0.0, 75.0, 75.0]]
[25.0, 25.0, 25.0, 25.0, 100.0]
[75.0, 75.0, 75.0, 75.0, 75.0]
[25.0, 75.0, 0.0, 75.0, 75.0]
[]
