# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [3]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [4]:
# your code here
print(np.__version__)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.14626771 0.07700987 0.82204811 0.56567761 0.28134087]
  [0.14132723 0.58740564 0.17841066 0.70971987 0.71565604]
  [0.56820206 0.87313325 0.59834713 0.05463188 0.68850287]]

 [[0.86561189 0.00163033 0.89647056 0.55193389 0.0423988 ]
  [0.19856994 0.97740359 0.2930169  0.91135297 0.03413883]
  [0.36500038 0.79109833 0.04056359 0.91383918 0.51598101]]]


In [6]:
# Method 2
a = np.random.rand(2,3,5)
print(a)

[[[0.91153493 0.71668352 0.51369489 0.67798604 0.1900535 ]
  [0.07181852 0.20582595 0.64694997 0.08272051 0.56809358]
  [0.72771884 0.9655536  0.24318119 0.28509179 0.80598246]]

 [[0.98315578 0.53268754 0.55273828 0.59130239 0.4791315 ]
  [0.58154032 0.31120281 0.7515384  0.91199359 0.6358762 ]
  [0.51236574 0.15179809 0.38769333 0.9673885  0.49103219]]]


In [7]:
# Method 3
a = np.random.randint(100,size=(2,3,5))
print(a)

[[[82 79 66 56 81]
  [ 4 25 38 65 80]
  [ 8 46 27 10 58]]

 [[26 88 85 52 74]
  [52 20 87 83 72]
  [65 69 52 50 98]]]


#### 4. Print *a*.


In [8]:
# your code here
print(a)

[[[82 79 66 56 81]
  [ 4 25 38 65 80]
  [ 8 46 27 10 58]]

 [[26 88 85 52 74]
  [52 20 87 83 72]
  [65 69 52 50 98]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [9]:
# your code here
b= np.ones((5,2,3))

#### 6. Print *b*.


In [10]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [11]:
# your code here
np.size(a)== np.size(b)
#yes, they do have the same size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [12]:
# your answer here
#No we can't, because they don't have the same shape

print(np.add(a,b))

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [13]:
# your code here
print(b.shape)
c = np.transpose(b,(1,2,0))

print(c)

(5, 2, 3)
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [14]:
# your code/answer here
d = np.add(a,c)
print(d)

#because they have the same shape

[[[83. 80. 67. 57. 82.]
  [ 5. 26. 39. 66. 81.]
  [ 9. 47. 28. 11. 59.]]

 [[27. 89. 86. 53. 75.]
  [53. 21. 88. 84. 73.]
  [66. 70. 53. 51. 99.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [15]:
# your code/answer here
print('a:',a)
print()
print('d:',d)

# the array d is equal to elements of array +1 because the array b 
#(which gives c, which adds to a) has only '1' values in it = identity matrix


a: [[[82 79 66 56 81]
  [ 4 25 38 65 80]
  [ 8 46 27 10 58]]

 [[26 88 85 52 74]
  [52 20 87 83 72]
  [65 69 52 50 98]]]

d: [[[83. 80. 67. 57. 82.]
  [ 5. 26. 39. 66. 81.]
  [ 9. 47. 28. 11. 59.]]

 [[27. 89. 86. 53. 75.]
  [53. 21. 88. 84. 73.]
  [66. 70. 53. 51. 99.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [16]:
# your code here
e = np.multiply(a,c)
print(e)

[[[82. 79. 66. 56. 81.]
  [ 4. 25. 38. 65. 80.]
  [ 8. 46. 27. 10. 58.]]

 [[26. 88. 85. 52. 74.]
  [52. 20. 87. 83. 72.]
  [65. 69. 52. 50. 98.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [17]:
# your code/answer here
# I found two ways of doing this:

# compare_arrays = a==e
# comparison = compare_arrays.all()
# print(comparison)  #--> this also gives True

np.array_equal(a,e)
#yes because array 1 has only '1' values in it

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [18]:
# your code here
d_max = np.amax(d)
print(d_max)
d_min = np.amin(d)
print(d_min)
d_mean = np.mean(d)
print(d_mean)

99.0
5.0
57.6


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [19]:
# your code here
f = np.empty((2,3,5))
print(f)

[[[82. 79. 66. 56. 81.]
  [ 4. 25. 38. 65. 80.]
  [ 8. 46. 27. 10. 58.]]

 [[26. 88. 85. 52. 74.]
  [52. 20. 87. 83. 72.]
  [65. 69. 52. 50. 98.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [20]:
# @Erin, I had trouble with indexing in an array thanks for your help :-)
print(d.shape)
# your code here

for d0 in range(d.shape[0]):
    for d1 in range(d.shape[1]):
        for d2 in range(d.shape[2]):
            if d[d0][d1][d2] > d_min and d[d0][d1][d2] < d_mean:
                 f[d0][d1][d2] = 25
            elif d[d0][d1][d2] < d_max and d[d0][d1][d2] > d_mean:
                 f[d0][d1][d2] = 75
            elif d[d0][d1][d2] == d_min:
                f[d0][d1][d2] = 0
            elif d[d0][d1][d2] == d_mean:
                f[d0][d1][d2] = 50
            elif d[d0][d1][d2] == d_max:
                f[d0][d1][d2] = 100

print(f)

(2, 3, 5)
[[[ 75.  75.  75.  25.  75.]
  [  0.  25.  25.  75.  75.]
  [ 25.  25.  25.  25.  75.]]

 [[ 25.  75.  75.  25.  75.]
  [ 25.  25.  75.  75.  75.]
  [ 75.  75.  25.  25. 100.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [21]:
# your code here
print(d)
print ('***')
print(f)

#Yes, because none of the numbers in d have a value == d-mean


[[[83. 80. 67. 57. 82.]
  [ 5. 26. 39. 66. 81.]
  [ 9. 47. 28. 11. 59.]]

 [[27. 89. 86. 53. 75.]
  [53. 21. 88. 84. 73.]
  [66. 70. 53. 51. 99.]]]
***
[[[ 75.  75.  75.  25.  75.]
  [  0.  25.  25.  75.  75.]
  [ 25.  25.  25.  25.  75.]]

 [[ 25.  75.  75.  25.  75.]
  [ 25.  25.  75.  75.  75.]
  [ 75.  75.  25.  25. 100.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [22]:
# your code here 
f = f.astype('object') #allows to acept any type of data in the array

for d0 in range(d.shape[0]):
    for d1 in range(d.shape[1]):
        for d2 in range(d.shape[2]):
            if d[d0][d1][d2] > d_min and d[d0][d1][d2] < d_mean:
                 f[d0][d1][d2] = 'B'
            elif d[d0][d1][d2] < d_max and d[d0][d1][d2] > d_mean:
                 f[d0][d1][d2] = 'D'
            elif d[d0][d1][d2] == d_min:
                f[d0][d1][d2] = 'A'
            elif d[d0][d1][d2] == d_mean:
                f[d0][d1][d2] = 'C'
            elif d[d0][d1][d2] == d_max:
                f[d0][d1][d2] = 'E'
                
print(f)

[[['D' 'D' 'D' 'B' 'D']
  ['A' 'B' 'B' 'D' 'D']
  ['B' 'B' 'B' 'B' 'D']]

 [['B' 'D' 'D' 'B' 'D']
  ['B' 'B' 'D' 'D' 'D']
  ['D' 'D' 'B' 'B' 'E']]]
