# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [131]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [132]:
# your code here
np.version.version

'1.19.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [133]:
# Method 1

a = np.random.random((2,3,5))
print(a)

[[[0.29452416 0.94976099 0.60631583 0.00906952 0.79350913]
  [0.95317934 0.19123601 0.96525882 0.26313621 0.04621162]
  [0.51907663 0.77910729 0.97404798 0.21145584 0.25879383]]

 [[0.48057027 0.95552141 0.59783183 0.16885896 0.72081613]
  [0.64638871 0.20190623 0.34030084 0.28101695 0.78075155]
  [0.59629868 0.71773562 0.30130065 0.77228553 0.70761275]]]


In [134]:
a = np.empty((2,3,5)) 
print(a)

[[[0.29452416 0.94976099 0.60631583 0.00906952 0.79350913]
  [0.95317934 0.19123601 0.96525882 0.26313621 0.04621162]
  [0.51907663 0.77910729 0.97404798 0.21145584 0.25879383]]

 [[0.48057027 0.95552141 0.59783183 0.16885896 0.72081613]
  [0.64638871 0.20190623 0.34030084 0.28101695 0.78075155]
  [0.59629868 0.71773562 0.30130065 0.77228553 0.70761275]]]


In [135]:
a = np.random.rand(2,3,5)
print(a)

[[[0.88572043 0.94129513 0.19585192 0.86345924 0.92874618]
  [0.4366692  0.17279891 0.53295533 0.72042238 0.13415363]
  [0.80214479 0.90368492 0.97388727 0.49211265 0.5260459 ]]

 [[0.04609933 0.27366916 0.57491908 0.47498388 0.02687822]
  [0.83588963 0.55404945 0.87948093 0.82406253 0.42762664]
  [0.88480963 0.78510375 0.73868149 0.02867942 0.06254743]]]


#### 4. Print *a*.


In [136]:
# your code here

print(a)

[[[0.88572043 0.94129513 0.19585192 0.86345924 0.92874618]
  [0.4366692  0.17279891 0.53295533 0.72042238 0.13415363]
  [0.80214479 0.90368492 0.97388727 0.49211265 0.5260459 ]]

 [[0.04609933 0.27366916 0.57491908 0.47498388 0.02687822]
  [0.83588963 0.55404945 0.87948093 0.82406253 0.42762664]
  [0.88480963 0.78510375 0.73868149 0.02867942 0.06254743]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [137]:
# your code here
b = np.ones((5,3,2),dtype=int)

#### 6. Print *b*.


In [138]:
# your code here
print(b)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [139]:
# your code here
print(a.size)
print(b.size)

print(2*3*5)
print(5*3*2)

#They have the same size, the product of 2*3*5 and 5*3*2 are both equal to 30

30
30
30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [140]:
# your answer here
print(np.add(a, b))
# b and a are both 3 dimensional array with different shapes, so array cannot be added.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [100]:
# your code here
c = np.transpose(b)
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [172]:
# your code/answer here

d = np.add(a, c)

print(d)

[[[1.88572043 1.94129513 1.19585192 1.86345924 1.92874618]
  [1.4366692  1.17279891 1.53295533 1.72042238 1.13415363]
  [1.80214479 1.90368492 1.97388727 1.49211265 1.5260459 ]]

 [[1.04609933 1.27366916 1.57491908 1.47498388 1.02687822]
  [1.83588963 1.55404945 1.87948093 1.82406253 1.42762664]
  [1.88480963 1.78510375 1.73868149 1.02867942 1.06254743]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [142]:
# your code/answer here
print(a)
print(d)

#The sum impacted each element of both list sperately. 

[[[0.88572043 0.94129513 0.19585192 0.86345924 0.92874618]
  [0.4366692  0.17279891 0.53295533 0.72042238 0.13415363]
  [0.80214479 0.90368492 0.97388727 0.49211265 0.5260459 ]]

 [[0.04609933 0.27366916 0.57491908 0.47498388 0.02687822]
  [0.83588963 0.55404945 0.87948093 0.82406253 0.42762664]
  [0.88480963 0.78510375 0.73868149 0.02867942 0.06254743]]]
[[[1.88572043 1.94129513 1.19585192 1.86345924 1.92874618]
  [1.4366692  1.17279891 1.53295533 1.72042238 1.13415363]
  [1.80214479 1.90368492 1.97388727 1.49211265 1.5260459 ]]

 [[1.04609933 1.27366916 1.57491908 1.47498388 1.02687822]
  [1.83588963 1.55404945 1.87948093 1.82406253 1.42762664]
  [1.88480963 1.78510375 1.73868149 1.02867942 1.06254743]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [143]:
# your code here

e = np.multiply(c, a)


#### 13. Does *e* equal to *a*? Why or why not?


In [144]:
# your code/answer here

print(e)
print(a)

e == a

# Yes, e = a, because c is 3-dimensional array with all values equaling to 1. 
#Thus each value of a multiplied by one equals the same value.

[[[0.88572043 0.94129513 0.19585192 0.86345924 0.92874618]
  [0.4366692  0.17279891 0.53295533 0.72042238 0.13415363]
  [0.80214479 0.90368492 0.97388727 0.49211265 0.5260459 ]]

 [[0.04609933 0.27366916 0.57491908 0.47498388 0.02687822]
  [0.83588963 0.55404945 0.87948093 0.82406253 0.42762664]
  [0.88480963 0.78510375 0.73868149 0.02867942 0.06254743]]]
[[[0.88572043 0.94129513 0.19585192 0.86345924 0.92874618]
  [0.4366692  0.17279891 0.53295533 0.72042238 0.13415363]
  [0.80214479 0.90368492 0.97388727 0.49211265 0.5260459 ]]

 [[0.04609933 0.27366916 0.57491908 0.47498388 0.02687822]
  [0.83588963 0.55404945 0.87948093 0.82406253 0.42762664]
  [0.88480963 0.78510375 0.73868149 0.02867942 0.06254743]]]


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [145]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean =np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9738872742085154
1.0268782237962926
1.5642476150833846


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [146]:
# your code here

f = np.empty((2,3,5))
print(f)

[[[0.88572043 0.94129513 0.19585192 0.86345924 0.92874618]
  [0.4366692  0.17279891 0.53295533 0.72042238 0.13415363]
  [0.80214479 0.90368492 0.97388727 0.49211265 0.5260459 ]]

 [[0.04609933 0.27366916 0.57491908 0.47498388 0.02687822]
  [0.83588963 0.55404945 0.87948093 0.82406253 0.42762664]
  [0.88480963 0.78510375 0.73868149 0.02867942 0.06254743]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [166]:
# First attempt
for i in d:
    for y in i:
        for z in y:
            if z > d_min:
                z = 25
                np.append(f,z)
            if z < d_max and z > d_mean:
                z = 75
                np.append(f,z)
            if z == d_mean:
                z = 50
                np.append(f,z)
            if z == d_max:
                z = 100
                np.append(f,z)
            
print(f)
               

[[[0.88572043 0.94129513 0.19585192 0.86345924 0.92874618]
  [0.4366692  0.17279891 0.53295533 0.72042238 0.13415363]
  [0.80214479 0.90368492 0.97388727 0.49211265 0.5260459 ]]

 [[0.04609933 0.27366916 0.57491908 0.47498388 0.02687822]
  [0.83588963 0.55404945 0.87948093 0.82406253 0.42762664]
  [0.88480963 0.78510375 0.73868149 0.02867942 0.06254743]]]


In [178]:
 = np.where(a<3,0,1)


[[[2.50000000e+01 2.50000000e+01 2.50000000e+01 2.50000000e+01
   2.50000000e+01]
  [2.50000000e+01 2.50000000e+01 2.50000000e+01 2.50000000e+01
   2.50000000e+01]
  [2.50000000e+01 2.50000000e+01 1.00000000e+02 2.50000000e+01
   2.50000000e+01]]

 [[2.50000000e+01 2.50000000e+01 2.50000000e+01 2.50000000e+01
   2.68782238e-02]
  [2.50000000e+01 2.50000000e+01 2.50000000e+01 2.50000000e+01
   2.50000000e+01]
  [2.50000000e+01 2.50000000e+01 2.50000000e+01 2.50000000e+01
   2.50000000e+01]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [169]:
# your code here

print(d)
print(f)

[[[1.88572043 1.94129513 1.19585192 1.86345924 1.92874618]
  [1.4366692  1.17279891 1.53295533 1.72042238 1.13415363]
  [1.80214479 1.90368492 1.97388727 1.49211265 1.5260459 ]]

 [[1.04609933 1.27366916 1.57491908 1.47498388 1.02687822]
  [1.83588963 1.55404945 1.87948093 1.82406253 1.42762664]
  [1.88480963 1.78510375 1.73868149 1.02867942 1.06254743]]]
[[[0.88572043 0.94129513 0.19585192 0.86345924 0.92874618]
  [0.4366692  0.17279891 0.53295533 0.72042238 0.13415363]
  [0.80214479 0.90368492 0.97388727 0.49211265 0.5260459 ]]

 [[0.04609933 0.27366916 0.57491908 0.47498388 0.02687822]
  [0.83588963 0.55404945 0.87948093 0.82406253 0.42762664]
  [0.88480963 0.78510375 0.73868149 0.02867942 0.06254743]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here