# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here

print(np.__version__)

1.19.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1

a = np.random.random((2,3,5))

In [4]:
# Method 2

In [5]:
# Method 3

#### 4. Print *a*.


In [6]:
# your code here

print(a)

[[[0.65639585 0.62949961 0.65470496 0.21179718 0.80336571]
  [0.02491028 0.26281816 0.14856198 0.41927933 0.78270364]
  [0.74717108 0.33595737 0.85554925 0.25714128 0.35581633]]

 [[0.40352308 0.17066764 0.96236633 0.85112748 0.92286052]
  [0.99983494 0.17903187 0.00252792 0.00575277 0.2621293 ]
  [0.49789553 0.47811279 0.42959952 0.19874762 0.89841892]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here

b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [8]:
# your code here

print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here

# You check the size of A and B and compare the numbers
print(np.size(a))
print(np.size(b))

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

# No I couldn't because the arrays have different dimensions
# print(np.add(a, b))

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here

c = b.reshape(2,3,5)

print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here

# Because of the reshaping of the array now they align
d = np.add(a, c)

print(d)

[[[1.65639585 1.62949961 1.65470496 1.21179718 1.80336571]
  [1.02491028 1.26281816 1.14856198 1.41927933 1.78270364]
  [1.74717108 1.33595737 1.85554925 1.25714128 1.35581633]]

 [[1.40352308 1.17066764 1.96236633 1.85112748 1.92286052]
  [1.99983494 1.17903187 1.00252792 1.00575277 1.2621293 ]
  [1.49789553 1.47811279 1.42959952 1.19874762 1.89841892]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here

# The are the same numbers but D has the same number + 1.0
print(a)
print()
print(d)

[[[0.65639585 0.62949961 0.65470496 0.21179718 0.80336571]
  [0.02491028 0.26281816 0.14856198 0.41927933 0.78270364]
  [0.74717108 0.33595737 0.85554925 0.25714128 0.35581633]]

 [[0.40352308 0.17066764 0.96236633 0.85112748 0.92286052]
  [0.99983494 0.17903187 0.00252792 0.00575277 0.2621293 ]
  [0.49789553 0.47811279 0.42959952 0.19874762 0.89841892]]]

[[[1.65639585 1.62949961 1.65470496 1.21179718 1.80336571]
  [1.02491028 1.26281816 1.14856198 1.41927933 1.78270364]
  [1.74717108 1.33595737 1.85554925 1.25714128 1.35581633]]

 [[1.40352308 1.17066764 1.96236633 1.85112748 1.92286052]
  [1.99983494 1.17903187 1.00252792 1.00575277 1.2621293 ]
  [1.49789553 1.47811279 1.42959952 1.19874762 1.89841892]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here

e = np.multiply(a, c)

print(e)

[[[0.65639585 0.62949961 0.65470496 0.21179718 0.80336571]
  [0.02491028 0.26281816 0.14856198 0.41927933 0.78270364]
  [0.74717108 0.33595737 0.85554925 0.25714128 0.35581633]]

 [[0.40352308 0.17066764 0.96236633 0.85112748 0.92286052]
  [0.99983494 0.17903187 0.00252792 0.00575277 0.2621293 ]
  [0.49789553 0.47811279 0.42959952 0.19874762 0.89841892]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here

# Yes they do because you multiply all the values of A with C (Which are all ones), so the results of A and E are the same
print(a)
print()
print(c)
print()
print(e)

[[[0.65639585 0.62949961 0.65470496 0.21179718 0.80336571]
  [0.02491028 0.26281816 0.14856198 0.41927933 0.78270364]
  [0.74717108 0.33595737 0.85554925 0.25714128 0.35581633]]

 [[0.40352308 0.17066764 0.96236633 0.85112748 0.92286052]
  [0.99983494 0.17903187 0.00252792 0.00575277 0.2621293 ]
  [0.49789553 0.47811279 0.42959952 0.19874762 0.89841892]]]

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]

[[[0.65639585 0.62949961 0.65470496 0.21179718 0.80336571]
  [0.02491028 0.26281816 0.14856198 0.41927933 0.78270364]
  [0.74717108 0.33595737 0.85554925 0.25714128 0.35581633]]

 [[0.40352308 0.17066764 0.96236633 0.85112748 0.92286052]
  [0.99983494 0.17903187 0.00252792 0.00575277 0.2621293 ]
  [0.49789553 0.47811279 0.42959952 0.19874762 0.89841892]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here

d_max = np.min(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.0025279235558755
1.0025279235558755
1.4802756079701072


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here

f = np.empty((2,3,5))

print(f)

[[[0.65639585 0.62949961 0.65470496 0.21179718 0.80336571]
  [0.02491028 0.26281816 0.14856198 0.41927933 0.78270364]
  [0.74717108 0.33595737 0.85554925 0.25714128 0.35581633]]

 [[0.40352308 0.17066764 0.96236633 0.85112748 0.92286052]
  [0.99983494 0.17903187 0.00252792 0.00575277 0.2621293 ]
  [0.49789553 0.47811279 0.42959952 0.19874762 0.89841892]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here

for i in range(d):
    if i > d_min:
        print(25)

print(d)

TypeError: only integer scalar arrays can be converted to a scalar index

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

print(d)
print()
print(f)

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here