# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
np.version.version

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a = np.random.random((2,3,5))

In [ ]:
#a = np.random.rand(2,3,5)

In [29]:
#a = np.empty((2,3,5))

#### 4. Print *a*.


In [4]:
print(a)

[[[0.32477206 0.64555235 0.27935086 0.54260587 0.58939083]
  [0.5842703  0.08718538 0.82161084 0.93983551 0.68001766]
  [0.11026034 0.61635228 0.61780757 0.69139471 0.67300248]]

 [[0.48912728 0.77143901 0.68698566 0.2595494  0.39927796]
  [0.87461811 0.14912491 0.79185022 0.51503026 0.02458013]
  [0.25778171 0.3798574  0.52268806 0.29602001 0.29501402]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [5]:
b = np.ones((5,2,3), dtype = int)

#### 6. Print *b*.


In [6]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [7]:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [8]:
#np.add(a, b)

#Can't add them, even though the size is the same, the shapes are different
a.shape == b.shape

False

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [9]:
c = b.reshape(2,3,5)
#print(c.shape)
#print(c)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [20]:
d = np.add(a, c)
a.shape == c.shape

True

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [21]:
print('a:', a)
 
print('\nd:', d)

print('\nsum:', a+1)

#c is a matrix of only 1s, so adding c to a is the same as adding 1 to the matrix a

d == a+1

a: [[[0.32477206 0.64555235 0.27935086 0.54260587 0.58939083]
  [0.5842703  0.08718538 0.82161084 0.93983551 0.68001766]
  [0.11026034 0.61635228 0.61780757 0.69139471 0.67300248]]

 [[0.48912728 0.77143901 0.68698566 0.2595494  0.39927796]
  [0.87461811 0.14912491 0.79185022 0.51503026 0.02458013]
  [0.25778171 0.3798574  0.52268806 0.29602001 0.29501402]]]

d: [[[1.32477206 1.64555235 1.27935086 1.54260587 1.58939083]
  [1.5842703  1.08718538 1.82161084 1.93983551 1.68001766]
  [1.11026034 1.61635228 1.61780757 1.69139471 1.67300248]]

 [[1.48912728 1.77143901 1.68698566 1.2595494  1.39927796]
  [1.87461811 1.14912491 1.79185022 1.51503026 1.02458013]
  [1.25778171 1.3798574  1.52268806 1.29602001 1.29501402]]]

sum: [[[1.32477206 1.64555235 1.27935086 1.54260587 1.58939083]
  [1.5842703  1.08718538 1.82161084 1.93983551 1.68001766]
  [1.11026034 1.61635228 1.61780757 1.69139471 1.67300248]]

 [[1.48912728 1.77143901 1.68698566 1.2595494  1.39927796]
  [1.87461811 1.14912491 1.791850

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [22]:
e = a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [23]:
print(e == a)

#c is a matrix of 1, 
#so multiplying a by c equals multiplying each value in a by 1, 
#which is why a = e

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [24]:
d_max = np.max(d)
print('Max:', d_max)
d_min = np.min(d)
print('Min:', d_min)
d_mean = np.mean(d)
print('Mean:', d_mean)

Max: 1.9398355132398581
Min: 1.024580126185306
Mean: 1.4972117722539202


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [25]:
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [26]:
print(d)

[[[1.32477206 1.64555235 1.27935086 1.54260587 1.58939083]
  [1.5842703  1.08718538 1.82161084 1.93983551 1.68001766]
  [1.11026034 1.61635228 1.61780757 1.69139471 1.67300248]]

 [[1.48912728 1.77143901 1.68698566 1.2595494  1.39927796]
  [1.87461811 1.14912491 1.79185022 1.51503026 1.02458013]
  [1.25778171 1.3798574  1.52268806 1.29602001 1.29501402]]]


In [44]:
empty = []
for i in np.nditer(d): 
    if i == d_max:
        i = 100
        empty.append(i)
#        print(i)
    elif i == d_min:
        i = 0
        empty.append(i)
#        print(i)
    elif i == d_mean:
        i = 50
        empty.append(i)
#        print(i)
    elif d_min < i < d_mean:
        i = 25
        empty.append(i)
#        print(i)
    else:
        i = 75
        empty.append(i)
#        print(i)

#print(empty)

a_empty = np.array(empty)
#print(a_empty)

f = a_empty.reshape(2,3,5)
#print(f)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [45]:
print('d: ', d)
print('\nf:', f)

#I'm pretty sure this is not the ideal solution because I used np, but it seems to work as well 
# but f is an array.

d:  [[[1.32477206 1.64555235 1.27935086 1.54260587 1.58939083]
  [1.5842703  1.08718538 1.82161084 1.93983551 1.68001766]
  [1.11026034 1.61635228 1.61780757 1.69139471 1.67300248]]

 [[1.48912728 1.77143901 1.68698566 1.2595494  1.39927796]
  [1.87461811 1.14912491 1.79185022 1.51503026 1.02458013]
  [1.25778171 1.3798574  1.52268806 1.29602001 1.29501402]]]

f: [[[ 25  75  25  75  75]
  [ 75  25  75 100  75]
  [ 25  75  75  75  75]]

 [[ 25  75  75  25  25]
  [ 75  25  75  75   0]
  [ 25  25  75  25  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [46]:
lstbonus = []
for i in np.nditer(d): 
    if i == d_max:
        i = 'E'
        lstbonus.append(i)
    elif i == d_min:
        i = 'A'
        lstbonus.append(i)
    elif i == d_mean:
        i = 'C'
        lstbonus.append(i)
    elif d_min < i < d_mean:
        i = 'B'
        lstbonus.append(i)
    else:
        i = 'D'
        lstbonus.append(i)
        
bonus = np.array(lstbonus)
bonus = bonus.reshape(2,3,5)
print(bonus)

[[['B' 'D' 'B' 'D' 'D']
  ['D' 'B' 'D' 'E' 'D']
  ['B' 'D' 'D' 'D' 'D']]

 [['B' 'D' 'D' 'B' 'B']
  ['D' 'B' 'D' 'D' 'A']
  ['B' 'B' 'D' 'B' 'B']]]


In [ ]:
#Same here using numpy, bonus is an array of strings