# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [66]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [67]:
# your code here
np.version.version

'1.18.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [68]:
# Method 1
a = np.random.random([2,3,5])


In [69]:
# Method 2


In [70]:
# Method 3

#### 4. Print *a*.


In [71]:
# your code here
print(a)

[[[0.40968667 0.10295414 0.54183241 0.14728196 0.3002726 ]
  [0.12682127 0.5498137  0.29250118 0.13268043 0.06546168]
  [0.01440197 0.06025672 0.67772196 0.07527298 0.87653057]]

 [[0.26549403 0.56898483 0.53548117 0.37846955 0.33704553]
  [0.3048301  0.13111294 0.21713098 0.94803308 0.48291521]
  [0.35204278 0.81461164 0.68503707 0.80895919 0.55980667]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [72]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [73]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [74]:
# your code here
print(a.size)
print(b.size)
"""Yes, Both 'a' and 'b' have same sizes. Size is the number of elements in each array."""

30
30


"Yes, Both 'a' and 'b' have same sizes. Size is the number of elements in each array."

#### 8. Are you able to add *a* and *b*? Why or why not?


In [75]:
# your answer here
print(np.add(a,b))

"""No, we cannot add a,b as the shapes of them are different because 'a' is a 3-Dimensional with 2 subgroups with 
3 rows and 5 elements whereas 'b' is a 3-Dimensional array with 5 subgroups 2 rows and 3 elements.
"""

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [76]:
# your code here
c = b.reshape(a.shape)
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [77]:
# your code/answer here
d = np.add(a,c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [78]:
# your code/answer here
print(a)
print()
print(d)

""" The difference between 'a' and 'd' in terms of values are 1. So, the relation is each element(d) = each element(a)
+ 1. We assigned array 'b' which consists of elements of 1's(ones) to c.  """

[[[0.40968667 0.10295414 0.54183241 0.14728196 0.3002726 ]
  [0.12682127 0.5498137  0.29250118 0.13268043 0.06546168]
  [0.01440197 0.06025672 0.67772196 0.07527298 0.87653057]]

 [[0.26549403 0.56898483 0.53548117 0.37846955 0.33704553]
  [0.3048301  0.13111294 0.21713098 0.94803308 0.48291521]
  [0.35204278 0.81461164 0.68503707 0.80895919 0.55980667]]]

[[[1.40968667 1.10295414 1.54183241 1.14728196 1.3002726 ]
  [1.12682127 1.5498137  1.29250118 1.13268043 1.06546168]
  [1.01440197 1.06025672 1.67772196 1.07527298 1.87653057]]

 [[1.26549403 1.56898483 1.53548117 1.37846955 1.33704553]
  [1.3048301  1.13111294 1.21713098 1.94803308 1.48291521]
  [1.35204278 1.81461164 1.68503707 1.80895919 1.55980667]]]


" The difference between 'a' and 'd' in terms of values are 1. So, the relation is each element(d) = each element(a)\n+ 1. We assigned array 'b' which consists of elements of 1's(ones) to c.  "

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [79]:
# your code here
e = np.multiply(a, c)


#### 13. Does *e* equal to *a*? Why or why not?


In [80]:
# your code/answer here
print(e)
print()
print(a)

""" 
Yes, Both 'e' and 'a' produces same result. We assigned array 'b' which consists of elements of 1's(ones) to c. So, 
we then multiplied every element of 'a' with 1's producing same result of e.
"""

[[[0.40968667 0.10295414 0.54183241 0.14728196 0.3002726 ]
  [0.12682127 0.5498137  0.29250118 0.13268043 0.06546168]
  [0.01440197 0.06025672 0.67772196 0.07527298 0.87653057]]

 [[0.26549403 0.56898483 0.53548117 0.37846955 0.33704553]
  [0.3048301  0.13111294 0.21713098 0.94803308 0.48291521]
  [0.35204278 0.81461164 0.68503707 0.80895919 0.55980667]]]

[[[0.40968667 0.10295414 0.54183241 0.14728196 0.3002726 ]
  [0.12682127 0.5498137  0.29250118 0.13268043 0.06546168]
  [0.01440197 0.06025672 0.67772196 0.07527298 0.87653057]]

 [[0.26549403 0.56898483 0.53548117 0.37846955 0.33704553]
  [0.3048301  0.13111294 0.21713098 0.94803308 0.48291521]
  [0.35204278 0.81461164 0.68503707 0.80895919 0.55980667]]]


" \nYes, Both 'e' and 'a' produces same result. We assigned array 'b' which consists of elements of 1's(ones) to c. So, \nwe then multiplied every element of 'a' with 1's producing same result of e.\n"

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [81]:
# your code here
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [82]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [92]:
# your code here
d = [[[element for element in row] for row in subgroup for subgroup in d]]
f = [[[element for element in row] for row in subgroup for subgroup in f]] 
# print(d)
# print()
# print(f)

for subgroup in d:
    for row in subgroup:
        for element in row:
            if (element > d_min) and (element < d_mean):
                f.index(element) = 25
            elif (element > d_mean) and (element < d_max):
                f.index(element) = 75
            elif (element == d_mean):
                f.index(element) = 50
            elif (element == d_min):
                f.index(element)= 0
            else:
                f.index(element) = 100

                

SyntaxError: cannot assign to function call (<ipython-input-92-1645c8ae6554>, line 18)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here