# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.version.version)

1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.9733275  0.37030631 0.0657859  0.73158284 0.56091301]
  [0.97111319 0.8728664  0.30938619 0.71320506 0.0797542 ]
  [0.58814451 0.36367135 0.67738424 0.08510776 0.45106522]]

 [[0.66277538 0.10085045 0.84290538 0.55450853 0.56892001]
  [0.85834266 0.91432741 0.20869112 0.25073194 0.92096837]
  [0.73640646 0.32371691 0.03726627 0.76550547 0.97197772]]]


In [4]:
# Method 2
a = np.random.normal(0, 1, (2, 3,5))
print(a)

[[[-1.58780568 -0.41671059 -0.73184555 -0.81257472  0.07726384]
  [ 0.82399055 -0.70449225  1.78489669 -1.44436127  0.5440011 ]
  [ 0.59728325 -0.17853372  0.1988063   0.27532359 -0.18634578]]

 [[-0.66581059 -0.39699521  0.49749815  0.58142566  0.64399422]
  [-0.00379633  1.42048856 -1.06081616  1.16526731  0.15126498]
  [ 0.84248691  0.68413889  0.00972089 -1.30577822 -1.7504307 ]]]


In [5]:
# Method 3
a = np.random.rand(2,3,5)
print(a)

[[[0.06261609 0.14348777 0.53397425 0.44655933 0.29114591]
  [0.85756463 0.4957112  0.96698781 0.4927445  0.93984892]
  [0.59467092 0.78611274 0.17104472 0.095683   0.94689238]]

 [[0.79919577 0.28039118 0.65263271 0.07441158 0.41001113]
  [0.43057547 0.62523308 0.01471594 0.50950908 0.70593249]
  [0.81060781 0.23031168 0.19572568 0.13380043 0.04443971]]]


#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.06261609 0.14348777 0.53397425 0.44655933 0.29114591]
  [0.85756463 0.4957112  0.96698781 0.4927445  0.93984892]
  [0.59467092 0.78611274 0.17104472 0.095683   0.94689238]]

 [[0.79919577 0.28039118 0.65263271 0.07441158 0.41001113]
  [0.43057547 0.62523308 0.01471594 0.50950908 0.70593249]
  [0.81060781 0.23031168 0.19572568 0.13380043 0.04443971]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
print("a and b have the same size:", a.size == b.size)

a and b have the same size: True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
add_ab = np.add(a,b)
print("No. Because shape of both arrays is different")

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
print("A Shape:", a.shape)
print("B Shape:", b.shape)
#Roos solution 
d = b.reshape(2,3,5)
print("Matrix d(Method 1):\n", d)
#Proposed solution
c = np.reshape(b,(2,3,5))

print("Matrix c(Method 2:)\n", c)

A Shape: (2, 3, 5)
B Shape: (5, 2, 3)
Matrix d(Method 1):
 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
Matrix c(Method 2:)
 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = np.add(a,c)
print("Now it works because a and c have the same shape")
print(d)

Now it works because a and c have the same shape
[[[1.06261609 1.14348777 1.53397425 1.44655933 1.29114591]
  [1.85756463 1.4957112  1.96698781 1.4927445  1.93984892]
  [1.59467092 1.78611274 1.17104472 1.095683   1.94689238]]

 [[1.79919577 1.28039118 1.65263271 1.07441158 1.41001113]
  [1.43057547 1.62523308 1.01471594 1.50950908 1.70593249]
  [1.81060781 1.23031168 1.19572568 1.13380043 1.04443971]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)
print(d)
print("All the values are summed. Value in position 0,0,0 in a is added to the value in the same position on array d")

[[[0.06261609 0.14348777 0.53397425 0.44655933 0.29114591]
  [0.85756463 0.4957112  0.96698781 0.4927445  0.93984892]
  [0.59467092 0.78611274 0.17104472 0.095683   0.94689238]]

 [[0.79919577 0.28039118 0.65263271 0.07441158 0.41001113]
  [0.43057547 0.62523308 0.01471594 0.50950908 0.70593249]
  [0.81060781 0.23031168 0.19572568 0.13380043 0.04443971]]]
[[[1.06261609 1.14348777 1.53397425 1.44655933 1.29114591]
  [1.85756463 1.4957112  1.96698781 1.4927445  1.93984892]
  [1.59467092 1.78611274 1.17104472 1.095683   1.94689238]]

 [[1.79919577 1.28039118 1.65263271 1.07441158 1.41001113]
  [1.43057547 1.62523308 1.01471594 1.50950908 1.70593249]
  [1.81060781 1.23031168 1.19572568 1.13380043 1.04443971]]]
All the values are summed. Value in position 0,0,0 in a is added to the value in the same position on array d


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = np.multiply(a,c)
print(e)

[[[0.06261609 0.14348777 0.53397425 0.44655933 0.29114591]
  [0.85756463 0.4957112  0.96698781 0.4927445  0.93984892]
  [0.59467092 0.78611274 0.17104472 0.095683   0.94689238]]

 [[0.79919577 0.28039118 0.65263271 0.07441158 0.41001113]
  [0.43057547 0.62523308 0.01471594 0.50950908 0.70593249]
  [0.81060781 0.23031168 0.19572568 0.13380043 0.04443971]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
print(e)
print(a)
print("They are both equal, because all the values of array c are 1, and since they are being multiplied by the element in the same postion (on array a) it will generate the same result")

[[[0.06261609 0.14348777 0.53397425 0.44655933 0.29114591]
  [0.85756463 0.4957112  0.96698781 0.4927445  0.93984892]
  [0.59467092 0.78611274 0.17104472 0.095683   0.94689238]]

 [[0.79919577 0.28039118 0.65263271 0.07441158 0.41001113]
  [0.43057547 0.62523308 0.01471594 0.50950908 0.70593249]
  [0.81060781 0.23031168 0.19572568 0.13380043 0.04443971]]]
[[[0.06261609 0.14348777 0.53397425 0.44655933 0.29114591]
  [0.85756463 0.4957112  0.96698781 0.4927445  0.93984892]
  [0.59467092 0.78611274 0.17104472 0.095683   0.94689238]]

 [[0.79919577 0.28039118 0.65263271 0.07441158 0.41001113]
  [0.43057547 0.62523308 0.01471594 0.50950908 0.70593249]
  [0.81060781 0.23031168 0.19572568 0.13380043 0.04443971]]]
They are both equal, because all the values of array c are 1, and since they are being multiplied by the element in the same postion (on array a) it will generate the same result


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print("Max:",d_max)
print("Min:",d_min)
print("Mean:",d_mean)

Max: 1.9669878067961326
Min: 1.0147159430172543
Mean: 1.4580845976908139


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty((2,3,5))
print(f)

[[[0.06261609 0.14348777 0.53397425 0.44655933 0.29114591]
  [0.85756463 0.4957112  0.96698781 0.4927445  0.93984892]
  [0.59467092 0.78611274 0.17104472 0.095683   0.94689238]]

 [[0.79919577 0.28039118 0.65263271 0.07441158 0.41001113]
  [0.43057547 0.62523308 0.01471594 0.50950908 0.70593249]
  [0.81060781 0.23031168 0.19572568 0.13380043 0.04443971]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
i = 0
j = 0
k = 0

for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 75
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100
            else:
                f[i][j][k] = 0


print("First method with repr:\n", repr(f))
print(np.array2string(f, separator = ','))

First method with repr:
 array([[[ 25.,  25.,  75.,  25.,  25.],
        [ 75.,  75., 100.,  75.,  75.],
        [ 75.,  75.,  25.,  25.,  75.]],

       [[ 75.,  25.,  75.,  25.,  25.],
        [ 25.,  75.,   0.,  75.,  75.],
        [ 75.,  25.,  25.,  25.,  25.]]])
[[[ 25., 25., 75., 25., 25.],
  [ 75., 75.,100., 75., 75.],
  [ 75., 75., 25., 25., 75.]],

 [[ 75., 25., 75., 25., 25.],
  [ 25., 75.,  0., 75., 75.],
  [ 75., 25., 25., 25., 25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here
print(d)
print(f)

[[[1.54695418 1.07991582 1.13713873 1.2926599  1.36289723]
  [1.84263304 1.81481557 1.27728337 1.45973173 1.0006835 ]
  [1.9397273  1.69481829 1.82264936 1.39575156 1.121547  ]]

 [[1.99622431 1.03731496 1.63485342 1.54652096 1.80828606]
  [1.61743908 1.63104334 1.73470586 1.49759475 1.64982775]
  [1.26950657 1.48260409 1.38764605 1.21532463 1.3174023 ]]]
[[[ 75.  25.  25.  25.  25.]
  [ 75.  75.  25.  25.   0.]
  [ 75.  75.  75.  25.  25.]]

 [[100.  25.  75.  75.  75.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  25.  25.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [19]:
# your code here
f = np.array(f, dtype = 'object')
f[f == 0] = 'E'
f[f == 25] = 'D'
f[f == 50] = 'C'
f[f == 75] = 'B'
f[f == 100] = 'A'

In [20]:
print(f)

[[['D' 'D' 'B' 'D' 'D']
  ['B' 'B' 'A' 'B' 'B']
  ['B' 'B' 'D' 'D' 'B']]

 [['B' 'D' 'B' 'D' 'D']
  ['D' 'B' 'E' 'B' 'B']
  ['B' 'D' 'D' 'D' 'D']]]
